---
title: "Untitled"
output: html_document
---
```{r}
library(spotifyr)
library(stringr)
library(dplyr)
library(tidyverse)
library(httr)
library(purrr)
library(readxl)
library(fossil)
library(FactoMineR)
library(corrplot)
library(factoextra)
library(gridExtra)
library(cluster)
library(Hmisc)
library(billboard)
library(MASS)
library(musictasteR)

```


```{r pressure, echo=FALSE}

Sys.setenv(SPOTIFY_CLIENT_ID = '76b887bef35c47c3a2f163b4ef96ad06')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '14a6cf275d804cd5983ac7a3a7b1531a')

access_token <- get_spotify_access_token()

df <- read_csv('/Users/miraekim/workspace/coursework/map535r/rubasic/working_files/150k_sample.csv')
df <- df[!is.na(df$key),]
billboard_df <- billboard::spotify_track_data
# Hmisc::describe(df)

df %>% group_by(album_year_4dgt, artist_name) %>% summarise(cnt=n()) %>% arrange(desc(cnt))

```

```{r}

#sumary csv

colnames(df)

summary_df <- df %>% group_by(album_year_4dgt) %>% 
summarise(danceability_avg=mean(danceability),
energy_avg=mean(energy),
key_avg=mean(key),
loudness_avg=mean(loudness),
mode_avg=mean(mode),
speechiness_avg=mean(speechiness),
acousticness_avg=mean(acousticness),
instrumentalness_avg=mean(instrumentalness),
liveness_avg=mean(liveness),
valence_avg=mean(valence),
tempo_avg=mean(tempo)
)
write.csv(summary_df, '/Users/miraekim/workspace/coursework/map535r/rubasic/working_files/avg_across_years_summary.csv')
```

```{r warning=F}

#prepare large dataframes, align columns 
df_edit <- df[c("track_uri","album_year_4dgt","track_name", "artist_name","duration_ms", "danceability","energy","key","loudness","mode","speechiness","acousticness","instrumentalness","liveness","valence","tempo")]
colnames(df_edit)[1] <- "track_id"
colnames(df_edit)[2] <- "year"
df_edit["top_or_not"] <- 0
billboard_edit <- billboard_df[c("track_id","year","track_name", "artist_name","duration_ms", "danceability","energy","key","loudness","mode","speechiness","acousticness","instrumentalness","liveness","valence","tempo")]
billboard_edit["top_or_not"] <- 1
full_test <- rbind(billboard_edit,df_edit)
full_test <- full_test[!(duplicated(full_test$track_name)& duplicated(full_test$artist_name)), ]

#filter out more artists
artist_test <- full_test %>% filter(top_or_not == 0) %>% group_by(year, artist_name) %>% slice(1:3)
artist_test%>% group_by(year, artist_name) %>% summarise(count=n())
artist_test <- artist_test %>% group_by(year) %>% slice(1:600) %>% ungroup()
artist_test %>% group_by(year) %>% summarise(count=n())

colnames(billboard_edit)
colnames(artist_test)
class(artist_test)

new_artist_test <-rbind(billboard_edit, artist_test)

per_year_test <- new_artist_test %>% group_by(year) %>% slice(1:600)
per_year_test



#Look 
new_artist_test %>% group_by(year, top_or_not) %>% summarise(count=n()) %>% ggplot(aes(x=year, y=count, fill=top_or_not)) + geom_bar(stat="identity", position=position_dodge())

ggplot(data=df2, aes(x=dose, y=len, fill=supp)) +
geom_bar(stat="identity", position=position_dodge())

colnames(df_edit)
colnames(billboard_edit)

df_edit <- df_edit[df_edit$duration_ms <= 300000,]
billboard_edit

#define function that runs regression
run_l_reg <-function(full_test) {
  # print(dim(non_billboard_df))
  # print(paste("original dataframe length:",dim(full_test)[1]))
  #dedup on track name and artist
  # print(paste("reduced dataframe length:",dim(full_test)[1]))
  res <- glm(top_or_not~.,family=binomial(link='logit'), data=full_test[-c(1:4)])
  bic <- step(res,direction="both",k=3,trace = FALSE)
  res2 <- glm(bic$model,family=binomial(link='logit'),data=full_test[-c(1:4)])
  anova_res <- anova(update(res2, ~1), res2, test='LR')
  return(list(bic, anova_res$`Pr(>Chi)`[2]))
  # return(full_test)
}

get_all_reg_models <- function(full_test) {
all_results <- list()
anova_list <- list()
return_list <- list()
for (year_input in 1960:2015) {
  print(year_input)
# for (year_input in 1960:1960) {
  full_test_year <- full_test %>% filter(year == year_input)
  result <- run_l_reg(full_test_year)
  all_results[paste0('year', as.character(year_input))] <- result[1]
  anova_list[paste0('year', as.character(year_input))] <- result[2]
}
return_list[['model_list']] <- all_results
return_list[['anova_list']] <- anova_list
return(return_list)
}

get_all_reg_models(new_artist_test)

save_result <- get_all_reg_models(new_artist_test)
save_result$anova_list
```

```{r}


names(all_results)
summary(all_results$year1960[[1]])
sort(unlist(anova_list))

#look at one year
billboard_test <- billboard_df %>% filter(year == 1969)
df_test <- df %>% filter(album_year_4dgt == 1969)
df_test2 <- df_test[c("track_uri","track_name","artist_name","danceability","energy","key","loudness","mode","speechiness","acousticness","instrumentalness","liveness","valence","tempo")]
colnames(df_test2)[1] <- "track_id"
df_test2["top_or_not"] <- 0
billboard_test2 <- billboard_test[c("track_id","track_name","artist_name","danceability","energy","key","loudness","mode","speechiness","acousticness","instrumentalness","liveness","valence","tempo")]
billboard_test2["top_or_not"] <- 1

#double check col names before combining the dfs
colnames(df_test2)
colnames(billboard_test2)

full_test <- rbind(df_test2,billboard_test2)

#full model
res1 <- glm(top_or_not~.,family=binomial(link='logit'),data=full_test[-c(1:4)])

#step wise to calibrate model
aic <- stepAIC(res,direction="both",trace = FALSE)

#check results
summary(aic)

#best aic model
res2 <- glm(aic$model,family=binomial(link='logit'),data=full_test[-c(1:4)])

#anova test to check significance
an <- anova(update(res2,~1), res2, test = "LR")

#save the models
# saveRDS(save_result$model_list, file="all_models2.rda")
m <- readRDS("musictasteR/data-raw/all_models2.rda")

#check against a new song
clean_up <- function(input) {
                list(
                  danceability = input$result$danceability,
                  energy = input$result$energy,
                  key = input$result$key,
                  loudness = input$result$loudness,
                  mode = input$result$mode,
                  speechiness = input$result$speechiness,
                  acousticness = input$result$acousticness,
                  instrumentalness = input$result$instrumentalness,
                  liveness = input$result$liveness,
                  valence = input$result$valence,
                  tempo = input$result$tempo,
                  duration_ms =  input$result$duration_ms,
                  # uri = final_list_filtered[[x]]["uri"],
                  # track_href = final_list_filtered[[x]]["track_href"],
                  # analysis_url = final_list_filtered[[x]]["analysis_url"],
                  # duration_ms = final_list_filtered[[x]]["duration_ms"],
                  # time_signature = final_list_filtered[[x]]["time_signature"],
                  artist_name = input$result$artist_name,
                  track_name = input$result$track_name,
                  album_year = input$result$year
                  # artist_id = final_list_filtered[[x]]["artist_uri"]
                )
  }

make_api_call <- function(audio_features_api,access_token) {
  analysis_result_call <- safely(RETRY)('GET', url = audio_features_api, query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) 
  if (is.null(analysis_result_call$result)) {
    print("ERROR in call for audio features")
    print(analysis_result_call$error)
  } else {
  analysis_result <- analysis_result_call$result %>% content
  track_href <- analysis_result$track_href
  track_result_call <- safely(RETRY)('GET', url = track_href, query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100)
  analysis_result <- analysis_result[c('danceability',
                                       'energy',
                                       'key',
                                       'loudness',
                                       'mode',
                                       'speechiness',
                                       'acousticness',
                                       'instrumentalness',
                                       'liveness',
                                       'valence',
                                       'tempo',
                                       'type',
                                       'uri',
                                       'track_href',
                                       'analysis_url',
                                       'duration_ms',
                                       'time_signature')]
    track_basic_trait_result <- track_result_call$result %>% content
    analysis_result['artist_name'] <- track_basic_trait_result$artists[[1]]$name
    analysis_result['track_name'] <- track_basic_trait_result$name
    analysis_result['year'] <- track_basic_trait_result$album$release_date
  return(analysis_result)
  }
}

data.table::.SD

track_uri = '2cjGujZxfRKo1NKTUy0fBU'
another_uri='5gXlabehojXdqcfFN8ncey'
another_uri2='6naxalmIoLFWR0siv8dnQQ'
audio_features_api <- str_glue('https://api.spotify.com/v1/audio-features/{track_uri}')
another_api <- str_glue('https://api.spotify.com/v1/audio-features/{another_uri}')
another_api2 <- str_glue('https://api.spotify.com/v1/audio-features/{another_uri2}')
access_token <- get_spotify_access_token()
analysis_result <- safely(make_api_call)(audio_features_api,access_token)
analysis_result2 <- safely(make_api_call)(another_api,access_token)
analysis_result3 <- safely(make_api_call)(another_api2,access_token)
new_song <- clean_up(analysis_result)
new_song2 <- clean_up(analysis_result2)
new_song3 <- clean_up(analysis_result3)

#returns dataframe with year, probability of it being in the top song, and year int, which is the integer
get_probability_of_billboard <- function(input_song, model) {
list_of_probability <- vector()
for (model_year in names(model)) {
  model_output <- model[model_year][[1]]
  probability <- as.numeric(predict(model_output,newdata=input_song,type="response")[[1]])
  # print(class(probability))
  list_of_probability[model_year] <- probability
}
df <- data.frame(list_of_probability,stringsAsFactors = F)
df <- data.frame(cbind(rownames(df),prob=as.double(df$list_of_probability)))
colnames(df) <- c('year', 'prob')
df['prob'] <- as.double(df$prob) 
df['year_int'] <- sapply(df$year,  function(x) {as.integer(substring(x,str_length(x)-3,str_length(x)))})
df['track_name'] <-  input_song$track_name
df['true_song_year'] <- substring(input_song$album_year, 1,4)
return(df)
}

df <- get_probability_of_billboard(new_song, m)
another_df <- get_probability_of_billboard(new_song2, m)
another_df2 <- get_probability_of_billboard(new_song3, m)

multiple_df<- rbind(df, another_df, another_df2)

library(data.table)
plot_probabilities <- function(input_dataframe, year_int_col_index, prob_col_index, track_name_col_index,  true_song_year_index) {
  #dataframe with year and probability
  colnames(input_dataframe)[year_int_col_index] <-"year_int"
  colnames(input_dataframe)[prob_col_index] <-"prob"
  colnames(input_dataframe)[track_name_col_index] <-"track_name"
  colnames(input_dataframe)[true_song_year_index] <- "true_song_year"
  input_dataframe['true_song_year_bool'] <- input_dataframe$true_song_year == input_dataframe$year_int
  
  DT <- data.table(input_dataframe)
    g <- ggplot(input_dataframe)+
      geom_line(aes(x=input_dataframe$year_int, y=as.double(input_dataframe$prob),group =input_dataframe$track_name, color=input_dataframe$track_name))+
      theme(legend.position="bottom", legend.direction="vertical")+
      labs(x='year',y='probability', title='Probability of being a top song', legend='tracks')+
      guides(size = "none",color=guide_legend("Track Name"), alpha="none")
    g <- g + geom_point(data=input_dataframe[input_dataframe$true_song_year_bool == T,],
                        aes(x=input_dataframe[input_dataframe$true_song_year_bool == T,]$year_int, 
                            y=input_dataframe[input_dataframe$true_song_year_bool == T,]$prob
                            ), color="black")
    # g <- g+ geom_text(aes(label=ifelse(true_song_year_bool == T,as.character(input_dataframe[input_dataframe$true_song_year_bool == T,]$prob),'')),hjust=0,vjust=0)
    g <- g + geom_point(data=DT[ , .SD[which.min(prob)], by = track_name],
                        aes(x=DT[ , .SD[which.min(prob)], by = track_name]$year_int, 
                            y=DT[ , .SD[which.min(prob)], by = track_name]$prob), color="red", shape=25, size=5)
    g <- g + geom_point(data=DT[ , .SD[which.max(prob)], by = track_name],
                        aes(x=DT[ , .SD[which.max(prob)], by = track_name]$year_int, 
                            y=DT[ , .SD[which.max(prob)], by = track_name]$prob), color="blue", shape=17, size=5)
    g <- g+ geom_text(data=input_dataframe[input_dataframe$true_song_year_bool == T,], aes(x=year_int,y=prob,label=paste0("release year: ", year_int) , alpha=0.8), hjust=-.06,vjust=-.06, size=3)
    g <- g+ geom_text(data=DT[ , .SD[which.min(prob)]], aes(x=year_int,y=prob, label=paste0("min. probability year: ", year_int) ,alpha=0.8), hjust=-.06,vjust=-.06, size=3)
    g <- g+ geom_text(data=DT[ , .SD[which.max(prob)]], aes(x=year_int,y=prob,label=paste0("max. probability year: ", year_int) ,alpha=0.8), hjust=-.06,vjust=-.06, size=3)
    return(g)
}


plot_probabilities(multiple_df, 3,2,4, 5)



```