---
title: "experiments_billboard"
author: "Roberta Conrad"
date: "19 11 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install the following libraries
#devtools::install_github('charlie86/spotifyr')
#install.packages('spotifyr')
#install.packages("billboard")

#library(spotifyr)
library(dplyr)
library(tidyverse)
library(httr)
library(stringr)
library(billboard)


#Akshay's spotify IDs
##fill in 
access_token <- get_spotify_access_token()

#function for getting id
get_id <- function(track_name, artist_name) {
  track_name = gsub(' ','%20',gsub("[^[:alnum:][:space:]]",'',track_name))
  artist_name =gsub(' ','%20',gsub("[^[:alnum:][:space:]]",'',artist_name))
  api <- str_glue('https://api.spotify.com/v1/search/?q=track:{track_name}%20artist:{artist_name}&type=track&limit=1')
  result <- RETRY('GET', url = api, query = list(access_token = access_token), quiet = TRUE, times = 1) %>% content 
  try(return(result$tracks$items[[1]]$id))
  # try(return(result))
}

test_id <- get_id('Smells like teen spirit', 'nirvana')

#See Audio Features for input song
res <- RETRY('GET', url = str_glue('https://api.spotify.com/v1/audio-features/{test_id}'), query = list(access_token = access_token), quiet = TRUE, times = 1) %>% content


#billboard (top music charts dataframe)
billboard::spotify_track_data
```

```{r}
#install.packages("billboard")

library(billboard)
#billboard (top music charts dataframe)
View(billboard::spotify_track_data)

spotify_track_data

```

```{r}
library(tidyverse)
library(plotly)

#plot_cross takes in a year and two dimension and returns a plot of all songs from this year mapped onto the two dimensions
#the data point added by the user will have year = 0
plot_cross <- function(database,year,x_axis=energy,y_axis=danceability){
  year <- enquo(year)
  x_axis <- enquo(x_axis)
  y_axis <- enquo(y_axis)
  x_axis_name <- as.character(x_axis)
  y_axis_name <- as.character(y_axis)
  tracklist <- database %>% filter(year == {!!year} | year == "0" ) %>% select(year,artist_name,track_name,!!x_axis,!!y_axis)
  
  #if we have a "new" element, we show this in a different color, otherwise we will simply display all points in grey
  if("new" %in% colnames(database))
    browse()
  { message("there is a new track in our databse!")
    color <- new}
  else color = "red"
  
  plot <- ggplot(tracklist, aes(!!x_axis, !!y_axis))  +
    geom_point(aes(text = track_name, artist= artist_name, color=color, size = 0.1),alpha = 1/2) + theme_minimal() + 
    xlim(0,1) + ylim (0,1)
  
   ggplotly(plot, tooltip = c("text", "artist",glue("{x_axis_name}"),glue("{y_axis_name}") ))
}
plot_cross(testdb ,2014,energy,valence)
#tests: does this function return a plotly element
# what happens for invalid years

```

```{r}

##user should be able to add a new song that is added to the database
#when new song is added, we create a new dataframe that adds a column new = 0 everywhere apart from the newly added song 
#use example track britney spears 

#add_a_song clones our database and adds a new column for our song
#takes in a database and a track, returns a modified database including this track with "new=0" and "year=0"
add_a_song <- function(database,new_song){
  database_modif <- database
  #initialize all songs we already know with new = 0
  database_modif$new <- 0
  #mark the track we added with a 1 so we can color by this 
  new_song$new <- 1
  #set year to zero so we can always see this point 
  new_song$year <- 0
  database_modif <- rbind(database_modif,new_song)
  return(database_modif)
}

#test track britney
#put this into a function that takes an existing song out of our database, and then compares the length of the old and new database with each other 
britney_track <- spotify_track_data_modified %>% filter(artist_name=="Britney Spears") %>% filter(dplyr::row_number()==1)
testdb <- add_a_song(spotify_track_data,britney_track)

#compare your song plots plot cross but adds the new track
compare_your_song <- function(){
  
}



#neuer plot mit modified datenbank
plot <- ggplot(spotify_track_data_modified[spotify_track_data_modified$year=="1960"|spotify_track_data_modified$year=="0"  ,], aes(energy, danceability)) +
  geom_point(aes(text = track_name, artist= artist_name, color=new, size = loudness),alpha = 1/3) + theme_minimal() + 
   xlim(0,1) + ylim (0,1)
  
ggplotly(plot, tooltip = c("text", "artist_name","energy","danceability" ))

```

