---
title: "Untitled"
author: "Akshay Sundar"
date: "12/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(tidyverse)
install.packages("plotly")
library(plotly)
```

```{r}

predict_pc_lm_temp <- function(song,year,mod1,mod2){
  index_val <- year-1959
  song$dim_1 <- predict(mod1[index_val][[1]],song)
  song$dim_2 <- predict(mod2[index_val][[1]],song)
  return(song)
}

plot_songs_clusters <- function(songs,year_taken){
  
  restr <- bb_data %>% filter(year==year_taken)
  restr$cluster_final <- paste0("Cluster ",substr(restr$hcpc_pca_cluster,6,7))
  
  songs_edit <- predict_pc_lm_temp(songs,year_taken,dim_pc_1,dim_pc_2)
  songs_edit$cluster_final <- "Manual Input songs"
  
  songs_edit <- songs_edit %>% select(track_name,artist_name,dim_1,dim_2,cluster_final)
  restr <- restr %>% select(track_name,artist_name,dim_1,dim_2,cluster_final)
  
  combined <- rbind(restr,songs_edit)
  
  plot <- combined %>% ggplot(aes(x=dim_1,y=dim_2)) + geom_point(aes(col=cluster_final)) + scale_fill_manual(name="Clusters",values = c("Cluster 1"="red","Cluster 2"="cyan","Cluster 3"="magenta","Manual Input songs"="yellow"))
  
  #plot <- plotly::ggplotly(plot)
  
  return(plot)
}

```

```{r}
temp1 <- read_csv("data-raw/billboard_samples_clustered.csv")
temp2 <- temp1 %>% filter(artist_name=="Pink Floyd")

d<-plot_songs_clusters(temp2,1990)
d


```

