---
title: "classifying_function"
author: "Akshay Sundar"
date: "12/10/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

set.seed(333)

library(tidyverse)
library(FactoMineR)
library(cluster)
```

Load Models
```{r}
k_model <- readRDS(model_k_clusters, file = "~/Documents/R Programming/Group Assignment/rubasic/rubasic/working_files/k_clusters_model.rda")
hcpc_model <- readRDS(model_hcpc_clusters, file = "~/Documents/R Programming/Group Assignment/rubasic/rubasic/working_files/hcpc_clusters_model.rda")
hcpc_pca_model <- readRDS(model_hcpc_pca_clusters, file = "~/Documents/R Programming/Group Assignment/rubasic/rubasic/working_files/hcpc_pca_clusters_model.rda")

dim_pc_1 <- readRDS(bb_princomp_lm_1, file = "~/Documents/R Programming/Group Assignment/rubasic/rubasic/working_files/bb_princomp_lm_1.rda")
dim_pc_2 <- readRDS(bb_princomp_lm_2, file = "~/Documents/R Programming/Group Assignment/rubasic/rubasic/working_files/bb_princomp_lm_2.rda")
```

Create Principal Dimensions for each year -
```{r}
predict_pc_lm <- function(song,year,mod1,mod2){
  index_val <- year-1959
  song$dim_1 <- predict(mod1[index_val][[1]],song)
  song$dim_2 <- predict(mod2[index_val][[1]],song)
  return(song)
}
```

Predict Clusters -
```{r}

classify_songs_k <- function(song,year,k_model){
  
  index_val <- year-1959
  k_model_res <- k_model[index_val][[1]]
  res_song <- song %>% select(dim_1,dim_2)
  clusters <- predict_pc_lm(as.data.frame(k_model_res$centers),2010,dim_pc_1,dim_pc_2) %>% select(dim_1,dim_2)
  class_sort <- data.frame()

  for (i in 1:nrow(song)) {
    temp1 <- res_song[i,]
    dist_mat <- dist(rbind(clusters,temp1)) 
    
    if(min(dist_mat[3],dist_mat[5],dist_mat[6])==dist_mat[3]){
      class_sort[i,1] <- 1
    }
    if(min(dist_mat[3],dist_mat[5],dist_mat[6])==dist_mat[5]){
      class_sort[i,1] <- 2
    }
    if(min(dist_mat[3],dist_mat[5],dist_mat[6])==dist_mat[6]){
      class_sort[i,1] <- 3
    }
    
  }
  
  song$cluster <- class_sort
  return(song)
}



```

