---
title: "trying_out_functions"
author: "Roberta Conrad"
date: "7 12 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(musictasteR)
??musictasteR
?hover_plot
data <- billboard::spotify_track_data

hover.plot(billboard::spotify_track_data,"1999",year,energy,danceability,track_name,artist_name,"Charts")

billboard::spotify_track_data



new_hover_plot <- function(database,filtered_year,year_col,x_axis,y_axis,track_name = track_name, artist_name = artist_name,title="Billboard Top 100 musical charts of "){
  #enquo all the columns that we need to use
  x_axis <- enquo(x_axis)
  y_axis <- enquo(y_axis)
  artist_name <- enquo(artist_name)
  track_name <- enquo(track_name)
  year_col <- enquo(year_col)

  tracklist <- database %>% filter(!!year_col == filtered_year | !!year_col == "0" ) %>%
    select(!!year_col,!!artist_name,!!track_name,!!x_axis,!!y_axis)

  plot <- ggplot(tracklist, aes(!!x_axis, !!y_axis))  +
    geom_point(aes(Trackname = (!!track_name), Artist= (!!artist_name), size = 0.1),alpha = 1/2) +
    ggtitle(glue::glue("{title}{filtered_year}")) +
    theme_minimal() +xlim(0,1) + ylim (0,1)

  plot_with_hover <- ggplotly(plot) %>% config(displayModeBar = F) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE)) %>%  layout(hoverlabel = list(bgcolor = "white",font = list(family = "sans serif",size = 12, color = "black")))

  return(plot_with_hover)
}

```


```{r}
apple = tibble(x = 1:3, y = list(1,2,3))
changed_order = apple[,c(2,1)]
colnames(britney_track)
new_col = data.frame(a = 1:23)[, "a", drop = TRUE]
colnames(new_col) <- colnames(britney_track)
is(spotify_track_data)

new_song <- spotify_track_data[1,]
new_song[1,] <- ""
new_song$artist_name <- song$track_artist_name
new_song$track_name <- song$artist_name
new_song$danceability <- song$danceability
new_song$energy <- song$energy
new_song$key <- song$key
new_song$loudness <- song$loudness
new_song$mode <- song$mode
new_song$speechiness<- song$speechiness
new_song$acousticness <- song$acousticness
new_song$instrumentalness <- song$instrumentalness
new_song$liveness <- song$liveness
new_song$valence <- song$valence
new_song$tempo <- song$tempo
new_song$year <- 0
#new_song$year <- substr(song$release_date, 1, 4)

#release date needs to be turned into year
a="2015-05-26"
substr(a, 1, 4)
```



```{r setup, include=FALSE}
library(stringr)
library(tidyverse)
library(plotly)
```

```{r}
predict_pc_lm_temp <- function(song,year,mod1,mod2){
  index_val <- year-1959
  song$dim_1 <- predict(mod1[index_val][[1]],song)
  song$dim_2 <- predict(mod2[index_val][[1]],song)
  return(song)
}
plot_songs_clusters <- function(songs,year_taken){
  songs$key <- as.numeric(songs$key)
  songs$mode <- as.numeric(songs$mode)
  colnames(songs)[colnames(songs)=="track_artist_name"]="track_name"
  
  restr <- bb_data %>% filter(year==year_taken)
  restr$cluster_final <- paste0("Cluster ",substr(restr$hcpc_pca_cluster,6,7))
  
  songs_edit <- predict_pc_lm_temp(songs,year_taken,dim_pc_1,dim_pc_2)
  songs_edit$cluster_final <- "Manual Input songs"
  
  songs_edit <- songs_edit %>% select(track_name,artist_name,dim_1,dim_2,cluster_final)
  restr <- restr %>% select(track_name,artist_name,dim_1,dim_2,cluster_final)
  
  combined <- rbind(restr,songs_edit)
  
  plot <- combined %>% ggplot(aes(x=dim_1,y=dim_2)) + geom_point(aes(col=cluster_final)) + scale_fill_manual(name="Clusters",values = c("Cluster 1"="#00b5ed","Cluster 2"="#f9776d","Cluster 3"="#a587ff","Manual Input songs"="#00c193")) +xlab("First Dimension")+ylab("Second Dimension")
  
  plot <- plotly::ggplotly(plot)%>%  plotly::layout(hoverlabel = list(bgcolor = "#ebebeb",font = list(family = "Arial", size = 12, color = "black"))) %>% plotly::config(displayModeBar = F)
  
  return(plot)
}
```

```{r}
temp1 <- read_csv("data-raw/billboard_samples_clustered.csv")
temp1
temp2 <- temp1 %>% filter(artist_name=="Pink Floyd")

temp3 <- get_tracks_artists("hey")


d<-plot_songs_clusters(temp3,1990)
d
```

Testing Format new songs
```{r}

library(billboard)

spotify_test_pull

formated_list <- musictasteR::format_new_songs(spotify_test_pull)
is.data.frame(formated_list)

"track_name" %in% colnames(formated_list)
"artist_name" %in% colnames(formated_list)

"energy" %in% colnames(formated_list)
year
```

```{r}
a <- get_tracks_artists("hey")
nrow(a) == 20
"track_artist_name" %in% colnames(a)
"artist_name" %in% colnames(a)
"album_name" %in% colnames(a)
"release_date" %in% colnames(a)
"track_artist" %in% colnames(a)

#should return 20 rows 
```



