---
title: "Non-billboard Tracks"
output: html_document
---
```{r}
library(spotifyr)
library(dplyr)
library(tidyverse)
library(httr)
library(purrr)
```

```{r}
#import dataset
# one_million_df <- read.csv('/Users/miraekim/workspace/coursework/map535r/group_project/r_group/one_million.csv', stringsAsFactors = FALSE)
#one million df has duplicates based on artist and song
# one_million_df <- unique(one_million_df[c('artist','song')])
sample_song <- read.csv('/Users/miraekim/workspace/coursework/map535r/rubasic/sample_songs_processed.csv')
```

```{r}
dim(sample_song)
sample_song
```

```{r}
billboard::spotify_track_data
```

```{r}

Sys.setenv(SPOTIFY_CLIENT_ID = '76b887bef35c47c3a2f163b4ef96ad06')
Sys.setenv(SPOTIFY_CLIENT_SECRET = '14a6cf275d804cd5983ac7a3a7b1531a')

access_token <- get_spotify_access_token()

#Samples
#get ID for a song					 
search <- 'https://api.spotify.com/v1/search/?q=track:dancing%20queen%20artist:abba&type=track&limit=1'
res <- RETRY('GET', url = str_glue(search),
                     query = list(access_token = access_token), quiet = TRUE, times = 1) %>% content
					 
#get the audio feature for a song
res <- RETRY('GET', url = 'https://api.spotify.com/v1/audio-features/?ids=5ghIJDpPoe3CfHMGu71E6T',
                     query = list(access_token = access_token), quiet = TRUE, times = 10) %>% content

```

Get track uri per song from the one million song database
```{r}
get_artist_id <- function(row) {
  track_name = gsub(' ','%20', gsub("[^[:alnum:][:space:]]",'',row['song']))
  artist_name =gsub(' ','%20', gsub("[^[:alnum:][:space:]]",'',row['artist']))
  api <- str_glue('https://api.spotify.com/v1/search/?q=track:{track_name}%20artist:{artist_name}&type=track&limit=1')
  access_token <- get_spotify_access_token()
  result <- RETRY('GET', url = api, query = list(access_token = 'BQDr1sA9pws_6bByOakxnSbATrTqusyyRrHsYQhxQWZ4-jlBqzk7WbhTB4Q3rJbrdp_9EhiV4wOoU6xOiK8'), quiet = TRUE, times = 1, pause_min = 1) %>% content 
    tryCatch({
      final_id <- suppressWarnings(result$tracks$items[[1]]$id)
      return (final_id)
    }, error=function(error_cond) {
      if (error_cond$message == 'subscript out of bounds') {
        return('ERROR subscript')
      }
    }
    , error=function(error_cond) {
      if (error_cond$message =='$ operator is invalid for atomic vectors') {
        result2 <- RETRY('GET', url = api, query = list(access_token = 'BQDr1sA9pws_6bByOakxnSbATrTqusyyRrHsYQhxQWZ4-jlBqzk7WbhTB4Q3rJbrdp_9EhiV4wOoU6xOiK8'), quiet = TRUE, times = 1, pause_min = 1) %>% content 
        print(error_cond$message)
        print(api)
        return(result2$tracks$items[[1]]$id)
      }
      else {
        print(error_cond$message)
        return('ERROR mysterious')
      }
    }
  )
}

```

Main script with for loop that gets spotify uri per song from one million song db
```{r warnings=FALSE, echo=FALSE}
# result
try <- trial_df3

for (i in 1:nrow(try)) {
  if (i %% 500 == 0) {
    print(i)
  }
  row <- try[i,]
  value <- get_artist_id(row)
  try[i,]$spotify_uri <- value
}
```

```{r}
#merge back to original df
trial_df2 <- try[!is.na(try$spotify_uri),]
complete_df <- merge(one_million_df, trial_df, by.x= c('artist', 'song'), by.y=c('artist', 'song'), all.x=TRUE)

#second trial
complete_df2 <- merge(complete_df, trial_df2, by.x= c('artist', 'song'), by.y=c('artist', 'song'), all.x=TRUE)

```


```{r}
#take a random sample of rows in the big df
trial_df2 <- complete_df[is.na(complete_df$spotify_uri),][sample(1:100000, 50000),colnames(complete_df)]
trial_df3 <- complete_df2[is.na(complete_df2$spotify_uri),][sample(1:100000, 10000),colnames(complete_df2)]

```

```{r}

#merge the final spotify_uri cols
# complete_df3[!is.na(complete_df3$spotify_uri.x),]
# 
# complete_df3$spotify_uri <- ifelse(is.na(complete_df3$spotify_uri.x), complete_df3$spotify_uri.y, complete_df3$spotify_uri.x)
# complete_df3[!is.na(complete_df3$spotify_uri),]

# complete_df3$spotify_uri.y <- NULL
# complete_df3$spotify_uri.x <- NULL
# count_df <- complete_df3[!is.na(complete_df3$spotify_uri),]
# write_to_df <- count_df %>% filter(!str_detect(tolower(spotify_uri),'error'))
# write.csv(write_to_df, '/Users/miraekim/workspace/coursework/map535r/group_project/r_group/current_results.csv',)
```

get music attributes script
```{r}
# df <- read.csv('/Users/miraekim/workspace/coursework/map535r/rubasic/non_billboard_songs_1.csv', stringsAsFactors = FALSE)

make_api_call <- function(audio_features_api,access_token) {
  analysis_result_call <- safely(RETRY)('GET', url = audio_features_api, query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) 
  if (is.null(analysis_result_call$result)) {
    print("ERROR in call for audio features")
    print(analysis_result_call$error)
  } else {
  analysis_result <- analysis_result_call$result %>% content
  track_href <- analysis_result$track_href
  analysis_result <- analysis_result[c('danceability',
                                       'energy',
                                       'key',
                                       'loudness',
                                       'mode',
                                       'speechiness',
                                       'acousticness',
                                       'instrumentalness',
                                       'liveness',
                                       'valence',
                                       'tempo',
                                       'type',
                                       'uri',
                                       'track_href',
                                       'analysis_url',
                                       'duration_ms',
                                       'time_signature')]
  return(analysis_result)
  # track_basic_trait_result_call <- safely(RETRY)('GET', url = track_href, query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100)
  # 
  # if (!is.null(track_basic_trait_result_call$result)) {
  #   track_basic_trait_result <- track_basic_trait_result_call$result %>% content 
  #   analysis_result[['artist_name']] <- track_basic_trait_result$artists[[1]]$name
  #   analysis_result[['artist_id']] <- track_basic_trait_result$artists[[1]]$id
  #   analysis_result[['track_name']] <- track_basic_trait_result$name
  #   return(analysis_result)
  # }
  # else {
  #   print("ERROR in track basic trait call")
  # }
  }
}

get_audio_features <- function(row) {
    track_uri <- as.character(row["track_uri"])
    audio_features_api <- str_glue('https://api.spotify.com/v1/audio-features/{track_uri}')
    access_token <- get_spotify_access_token()
    analysis_result <- safely(make_api_call)(audio_features_api,access_token)
    if (is.null(analysis_result$error)) {
      return(analysis_result)
    } else {
      print("ERROR in overall call")
      print(analysis_result$error)
    }
}
```

#Try on one 
```{r}
rez <- get_audio_features(unlist(df[53,]))
rez$result
# $message
unlist(df[1,])
test_list <- list()
test_list["track_uri"]<- c('bogus')
unlist(test_list)


unlist(df[51,])["track_uri"]
track_uri <- 'bogus'
track_uri2 <- df[53,]$track_uri
audio_features_api <- str_glue('https://api.spotify.com/v1/audio-features/{track_uri2}')


# thing <- possibly(make_api_call, otherwise='ERROR')(audio_features_api,access_token)
thing <- safely(make_api_call)(audio_features_api,access_token)
is.null(thing$error)

```



```{r warnings=FALSE}
head_of_df <- df

final_list <- list()
fail_list <- list()

for (i in 1:nrow(head_of_df)) {
  if (i %% 20 == 0) {
    print(i)
    Sys.sleep(sample(seq(0.5, 2.5, 0.5), 1))
  }
  row <- unlist(head_of_df[i,])
  api_result <- get_audio_features(row)
  #error hndling
  if (is.null(api_result$result)) {
    #wrong url
    if (api_result$message == "Must specify at least one of url or handle") {
      print(paste("Error in id", i))
      # return("URL misinput error")
    } else {
      print(paste('Other kind of error in id', i))
      print(api_result$message)
    }
    ## put other error handling here
  } else {
    final_row <- c(unlist(row[c("track_name", "track_uri", "album_name", "album_year", "album_year_4dgt", "artist_name", "artist_uri")]), unlist(api_result$result))
    final_list[[i]] <- final_row
  }
}

final_list_filtered <- Filter(Negate(is.null), final_list)

massive <- map_df(seq_len(length(final_list_filtered)), function(x) {
                list(
                  track_name = final_list_filtered[[x]]["track_name"],
                  track_uri = final_list_filtered[[x]]["track_uri"],
                  album_name = final_list_filtered[[x]]["album_name"],
                  album_year = final_list_filtered[[x]]["album_year"],
                  album_year_4dgt = final_list_filtered[[x]]["album_year_4dgt"],
                  danceability = final_list_filtered[[x]]["danceability"],
                  energy = final_list_filtered[[x]]["energy"],
                  key = final_list_filtered[[x]]["key"],
                  loudness = final_list_filtered[[x]]["loudness"],
                  mode = final_list_filtered[[x]]["mode"],
                  speechiness = final_list_filtered[[x]]["speechiness"],
                  acousticness = final_list_filtered[[x]]["acousticness"],
                  instrumentalness = final_list_filtered[[x]]["instrumentalness"],
                  liveness = final_list_filtered[[x]]["liveness"],
                  valence = final_list_filtered[[x]]["valence"],
                  tempo = final_list_filtered[[x]]["tempo"],
                  type = final_list_filtered[[x]]["type"],
                  uri = final_list_filtered[[x]]["uri"],
                  track_href = final_list_filtered[[x]]["track_href"],
                  analysis_url = final_list_filtered[[x]]["analysis_url"],
                  duration_ms = final_list_filtered[[x]]["duration_ms"],
                  time_signature = final_list_filtered[[x]]["time_signature"],
                  artist_name = final_list_filtered[[x]]["artist_name"],
                  artist_id = final_list_filtered[[x]]["artist_uri"]
                )})

write.csv(massive, '/Users/miraekim/workspace/coursework/map535r/rubasic/working files/sample_music_features.csv')

# result <- RETRY('GET', url = 'https://api.spotify.com/v1/audio-features/7rAKdUk7EDHdKRc8BzLw73', query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) %>% content
```

```{r}

#get songs by hipster album then track
#Not used because we have to search by album
access_token <- get_spotify_access_token()

album_query <- RETRY('GET', url = 'https://api.spotify.com/v1/search?q=album:a*%20year:1961%20&type=album', query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) %>% content

res <- album_query %>% .$albums %>% .$items
albums <- map_df(seq_len(length(res)), function(x) {
            list(
                # track_name = res[[x]]$name,
                # track_uri = gsub('spotify:track:', '', res[[x]]$uri),
                artist_name = res[[x]]$artists[[1]]$name,
                artist_uri = res[[x]]$artists[[1]]$id,
                album_name = res[[x]]$name,
                album_id = res[[x]]$id,
                album_year= res[[x]]$release_date,
                album_tracks= res[[x]]$total_tracks
            )
        })
album_id <- albums$album_id[1]

track_query <-  RETRY('GET', url = str_glue('https://api.spotify.com/v1/albums/{album_id}'), query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) %>% content

track_res <- track_query %>% .$tracks %>% .$items
tracks <- map_df(seq_len(length(track_res)), function(x) {
            list(
                track_name = track_res[[x]]$name,
                track_uri =track_res[[x]]$uri,
                artist_name = track_res[[x]]$artists[[1]]$name,
                artist_uri = track_res[[x]]$artists[[1]]$id
          )
        })
```

Script that searches by year based on one letter string with wildcard  
```{r}
#get songs just by track
all_tracks <- list()
for (letter in letters[1:26]) {
  access_token <- get_spotify_access_token()
  for (year in 1960:2017) {
    track_search <-  paste0(letter,'*')
    # print(track_search)
    url_built <- str_glue('https://api.spotify.com/v1/search?q=track:{track_search}%20year:{year}&limit=50&offset=60&type=track')
    # print(url_built)
      res <- RETRY('GET', url = url_built, query = list(access_token = access_token), quiet = TRUE, times = 1, pause_min = 100) %>% content
    res <- (res %>% .$tracks %>% .$items)
    all_tracks <- append(all_tracks,res)
    # break
  }
  # break
}

#transforms list of results into a dataframe
tracks_df <- map_df(seq_len(length(all_tracks)), function(x) {
                list(
                    track_name = all_tracks[[x]]$name,
                    track_uri = gsub('spotify:track:', '', all_tracks[[x]]$uri),
                    artist_name = all_tracks[[x]]$artists[[1]]$name,
                    artist_uri = all_tracks[[x]]$artists[[1]]$id,
                    album_name = all_tracks[[x]]$album$name,
                    album_id = all_tracks[[x]]$album$id,
                    album_year= all_tracks[[x]]$album$release_date
                )
            })
  
# create field with album year and count how maany songs per year
massive  %>% mutate(album_year_4dgt=substr(album_year,1,4)) %>% ggplot(aes(x=album_year_4dgt)) + geom_histogram(stat='count')
    
sample_by_year <- tracks_df %>% mutate(album_year_4dgt=substr(album_year,1,4) ) %>% group_by(album_year_4dgt)

# write.csv(sample_by_year,'/Users/miraekim/workspace/coursework/map535r/rubasic/avg_songs.csv')
```


```{r}
#load avg songs
df <- read.csv('/Users/miraekim/workspace/coursework/map535r/rubasic/avg_songs.csv', stringsAsFactors = FALSE)
```

```{r}
#combine with 
massive <- rbind(df[c("track_name","track_uri", "artist_name","artist_uri","album_name","album_id","album_year")],tracks_df)

#dedup on track uri 
massive = massive[!duplicated((massive)$track_uri), ]
```

```{r}
trial <- head_of_df[1:1000,]
trial %>% group_by(album_year_4dgt, artist_name) %>% summarise(count=n()) %>% arrange(desc(count))

#code to take only 2 from each album_year, artist name group
head_of_df %>% 
  group_by(album_year_4dgt, artist_name) %>% 
  slice(1:2) %>% filter(artist_name == "The Beatles")
```

