---
title: "experiments_billboard"
author: "Roberta Conrad"
date: "19 11 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#install the following libraries
#devtools::install_github('charlie86/spotifyr')
install.packages('spotifyr')
install.packages("billboard")

library(spotifyr)
library(dplyr)
library(tidyverse)
library(httr)
library(stringr)
library(billboard)


#Akshay's spotify IDs
##fill in 
access_token <- get_spotify_access_token()

#function for getting id
get_id <- function(track_name, artist_name) {
  track_name = gsub(' ','%20',gsub("[^[:alnum:][:space:]]",'',track_name))
  artist_name =gsub(' ','%20',gsub("[^[:alnum:][:space:]]",'',artist_name))
  api <- str_glue('https://api.spotify.com/v1/search/?q=track:{track_name}%20artist:{artist_name}&type=track&limit=1')
  result <- RETRY('GET', url = api, query = list(access_token = access_token), quiet = TRUE, times = 1) %>% content 
  try(return(result$tracks$items[[1]]$id))
  # try(return(result))
}

test_id <- get_id('Smells like teen spirit', 'nirvana')

#See Audio Features for input song
res <- RETRY('GET', url = str_glue('https://api.spotify.com/v1/audio-features/{test_id}'), query = list(access_token = access_token), quiet = TRUE, times = 1) %>% content


#billboard (top music charts dataframe)
billboard::spotify_track_data
```


```{r}
library(tidyverse)
library(plotly)
library(magrittr)
library(billboard)

##user should be able to add a new song that is added to the database
#when new song is added, we create a new dataframe that adds a column new = 0 everywhere apart from the newly added song 
#use example track britney spears 

#add_a_song clones our database and adds a new column for our song
#takes in a database and a track, returns a modified database including this track with "new=0" and "year=0"
add_a_song <- function(database,new_song){
  database_modif <- database
  new_song$year <- 0
  database_modif <- rbind(database_modif,new_song)
  return(database_modif)
}

#test track britney
#put this into a function that takes an existing song out of our database, and then compares the length of the old and new database with each other 
britney_track <- spotify_track_data %>% filter(artist_name=="Britney Spears") %>% filter(dplyr::row_number()==1)

new_database <- add_a_song(spotify_track_data,britney_track)



new_hover_plot <- function(database,filtered_year,year_col,x_axis,y_axis,track_name = track_name, artist_name = artist_name,title="Billboard Top 100 musical charts of "){
  #enquo all the columns that we need to use
  x_axis <- enquo(x_axis)
  y_axis <- enquo(y_axis)
  artist_name <- enquo(artist_name)
  track_name <- enquo(track_name)
  year_col <- enquo(year_col)

  tracklist <- database %>% filter(!!year_col == filtered_year | !!year_col == "0" ) %>%
    select(!!year_col,!!artist_name,!!track_name,!!x_axis,!!y_axis)
  
  
    plot <- ggplot(tracklist, aes(!!x_axis, !!y_axis,fill=!!year_col))  + guides(fill= "none") + 
    geom_point(aes(Trackname = (!!track_name), Artist= (!!artist_name), size = 0.1),alpha = 1/2) +  
    ggtitle(glue::glue("{title}{filtered_year}")) +
    theme_minimal() +xlim(0,1) + ylim (0,1)




  plot_with_hover <- ggplotly(plot) %>% config(displayModeBar = F) %>% layout(xaxis=list(fixedrange=TRUE)) %>% layout(yaxis=list(fixedrange=TRUE)) %>%  layout(hoverlabel = list(bgcolor = "white",font = list(family = "sans serif",size = 12, color = "black")))

  return(plot_with_hover)
}

#add error message if year in the wrong range! 
new_hover_plot(new_database ,"2009",year,energy,danceability,track_name,artist_name,"Charts")

```

```{r}



```

